version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:changeme -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  create-token:
    image: curlimages/curl:8.7.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: >
      sh -c "
        sleep 10 &&
        curl -u elastic:changeme -X POST 'http://elasticsearch:9200/_security/api_key' -H 'Content-Type: application/json' -d '{\"name\": \"my-api-key\"}' > /output/api_key.json
      "
    volumes:
      - ./output:/output

volumes:
  esdata: